name: CI on Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
     env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
        NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0' 

      - name: Install Dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate



      - name: Build
        run: npm run build
