name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" -t my-image:latest .

      - name: Push Docker image
        run: docker push my-image:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull mayurbaravkar07/my-image:latest
            sudo docker stop my-image || true
            sudo docker rm my-image || true
            sudo docker run -e DATABASE_URL="${{ secrets.DATABASE_URL }}" --restart=always -d --name my-image -p 3000:3000 mayurbaravkar07/my-image:latest
