name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    # - name: Prepare Dockerfile
    #   run:  ./Dockerfile

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: mayurbaravkar07/issue-tracker-aws:latest

    - name: Verify Pushed Image
      run: docker pull mayurbaravkar07/issue-tracker-aws:latest


    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull mayurbaravkar07/issue-tracker-aws:latest
          sudo docker stop issue-tracker-aws || true
          sudo docker rm issue-tracker-aws || true
          sudo docker run -e DATABASE_URL="${{ secrets.DATABASE_URL }}" --restart=always -d --name issue-tracker-aws -p 3000:3000 mayurbaravkar07/issue-tracker-aws:latest
